# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Attributes1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str


class Header(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    attributes: Attributes1


class Attributes2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: str


class Image(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str | None = None
    attributes: Attributes2
    field_atype: str | None = None


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    access_level: str
    licence_ids: list[int]
    id: int


class Action1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    data: Data


class Attributes3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    has_initial_focus: bool
    text: str
    label: str
    icon: str
    action: Action1


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    attributes: Attributes3


class Attributes5(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str | None = None


class Tag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    attributes: Attributes5


class Data1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    type: str


class Action2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    data: Data1


class Attributes6(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    text: str
    label: str
    icon: str
    action: Action2


class Button(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    attributes: Attributes6


class Attributes4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tags: list[Tag] | None = None
    text: str | None = None
    buttons: list[Button] | None = None


class ContentItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    attributes: Attributes4


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: Header
    image: Image
    actions: list[Action]
    content: list[ContentItem]
    type: None
    id: None
    active_tab: None
    items: None
    text: None
    label: None
    tab: None
    paging: None


class VodHero(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    field_zone: str
    attributes: Attributes
    style: None
