# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: None
    attributes: None
    title: str
    access_level: str
    type: str
    content_download: None
    description: str
    long_description: str
    duration: None
    thumbnail_url: None
    max_height: None
    online_playback: None
    computed_releases: None
    watch_status: str
    id: int
    cover_url: str
    season_count: str | None = None
    small_cover_url: str
    poster_url: str
    favourite: bool
    favourite_channel: str
    has_permission: bool
    is_related: bool
    has_permission_granted_on_sign_in: bool
    vod_count: str | None = None


class Paging(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    more_data_available: bool
    last_seen: str


class SeasonBucketRelated(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: None
    image: None
    actions: None
    content: None
    id: None
    type: str
    active_tab: None
    items: list[Item]
    series: None
    season_id: int
    seasons: None
    tab: str
    bucket_title: str
    series_id: int
    paging: Paging
    text: None
    label: None
