# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Data(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    tab: str


class Action(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    data: Data


class Attributes1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    label: str
    action: Action


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    attributes: Attributes1
    id: None
    type: None
    title: None
    description: None
    long_description: None
    cover_url: None
    small_cover_url: None
    season_count: None
    poster_url: None
    access_level: None
    favourite: None
    watch_status: None
    favourite_channel: None
    has_permission: None
    is_related: None
    has_permission_granted_on_sign_in: None


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: None
    image: None
    actions: None
    content: None
    type: str
    id: int
    active_tab: str
    items: list[Item]
    text: None
    label: None
    tab: None
    paging: None


class Desktop(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display: str


class Tv(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display: str


class Style(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    desktop: Desktop
    tv: Tv
    mobile: None
    tablet: None


class VodTabs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    field_zone: str
    attributes: Attributes
    style: Style
