"""ScheduleModel, strict to a type checker, all-optional at runtime.

A type checker reads the strict model, so every field carries the type and
the requiredness the schema recorded. At runtime the all-optional copy is imported
instead, so a response that has drifted still parses and a field the data is
missing is None despite what its type hint says.
"""

from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import ScheduleModel as OptionalModel
from .strict_models import ScheduleModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Action,
        Action1,
        Action2,
        Action3,
        Action4,
        Action5,
        Actions,
        AfterElement,
        Apply,
        Attributes,
        Attributes1,
        Attributes10,
        Attributes11,
        Attributes12,
        Attributes13,
        Attributes14,
        Attributes15,
        Attributes16,
        Attributes17,
        Attributes18,
        Attributes19,
        Attributes2,
        Attributes20,
        Attributes3,
        Attributes4,
        Attributes5,
        Attributes6,
        Attributes7,
        Attributes8,
        Attributes9,
        Back,
        Button,
        Card,
        ComputedRelease,
        ContentItem,
        Data,
        Data2,
        Data4,
        Data5,
        Element,
        Element1,
        Element2,
        Filter,
        Forward,
        Group,
        HeaderItem,
        Icon,
        Icon1,
        Icon2,
        Next,
        Option,
        Reset,
        ScheduleModel,
        Style,
        Style10,
        Style11,
        Style2,
        Style3,
        Style4,
        Style5,
        Style6,
        Style7,
        Style8,
        Style9,
        Tag,
        Text,
        Text1,
        Title,
        Title1,
        Title2,
    )
else:
    from .optional_models import (
        Action,
        Action1,
        Action2,
        Action3,
        Action4,
        Action5,
        Actions,
        AfterElement,
        Apply,
        Attributes,
        Attributes1,
        Attributes10,
        Attributes11,
        Attributes12,
        Attributes13,
        Attributes14,
        Attributes15,
        Attributes16,
        Attributes17,
        Attributes18,
        Attributes19,
        Attributes2,
        Attributes20,
        Attributes3,
        Attributes4,
        Attributes5,
        Attributes6,
        Attributes7,
        Attributes8,
        Attributes9,
        Back,
        Button,
        Card,
        ComputedRelease,
        ContentItem,
        Data,
        Data2,
        Data4,
        Data5,
        Element,
        Element1,
        Element2,
        Filter,
        Forward,
        Group,
        HeaderItem,
        Icon,
        Icon1,
        Icon2,
        Next,
        Option,
        Reset,
        ScheduleModel,
        Style,
        Style10,
        Style11,
        Style2,
        Style3,
        Style4,
        Style5,
        Style6,
        Style7,
        Style8,
        Style9,
        Tag,
        Text,
        Text1,
        Title,
        Title1,
        Title2,
    )

__all__ = [
    "Action",
    "Action1",
    "Action2",
    "Action3",
    "Action4",
    "Action5",
    "Actions",
    "AfterElement",
    "Apply",
    "Attributes",
    "Attributes1",
    "Attributes10",
    "Attributes11",
    "Attributes12",
    "Attributes13",
    "Attributes14",
    "Attributes15",
    "Attributes16",
    "Attributes17",
    "Attributes18",
    "Attributes19",
    "Attributes2",
    "Attributes20",
    "Attributes3",
    "Attributes4",
    "Attributes5",
    "Attributes6",
    "Attributes7",
    "Attributes8",
    "Attributes9",
    "Back",
    "Button",
    "Card",
    "ComputedRelease",
    "ContentItem",
    "Data",
    "Data2",
    "Data4",
    "Data5",
    "Element",
    "Element1",
    "Element2",
    "Filter",
    "Forward",
    "Group",
    "HeaderItem",
    "Icon",
    "Icon1",
    "Icon2",
    "Next",
    "Option",
    "Reset",
    "ScheduleModel",
    "Style",
    "Style10",
    "Style11",
    "Style2",
    "Style3",
    "Style4",
    "Style5",
    "Style6",
    "Style7",
    "Style8",
    "Style9",
    "Tag",
    "Text",
    "Text1",
    "Title",
    "Title1",
    "Title2",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> ScheduleModel:
    """Read a downloaded file into ScheduleModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
