# ruff: noqa: D100
from typing import TYPE_CHECKING

from good_ass_pydantic_integrator import load

from .optional_models import VodModel as OptionalModel
from .strict_models import VodModel as StrictModel

if TYPE_CHECKING:
    from .strict_models import (
        Action,
        Action1,
        Action2,
        Action3,
        Action4,
        Attributes,
        Attributes1,
        Attributes2,
        Attributes3,
        Attributes4,
        Attributes5,
        Attributes6,
        Attributes7,
        Attributes8,
        Attributes9,
        Button,
        ContentDownload,
        ContentItem,
        Data,
        Data1,
        Data3,
        Desktop,
        Element,
        Element1,
        GroupName,
        Header,
        Image,
        Item,
        Mobile,
        Paging,
        Style,
        Style1,
        Style2,
        Style3,
        Tablet,
        Tag,
        Text,
        Tv,
        VodModel,
    )
else:
    from .optional_models import (
        Action,
        Action1,
        Action2,
        Action3,
        Action4,
        Attributes,
        Attributes1,
        Attributes2,
        Attributes3,
        Attributes4,
        Attributes5,
        Attributes6,
        Attributes7,
        Attributes8,
        Attributes9,
        Button,
        ContentDownload,
        ContentItem,
        Data,
        Data1,
        Data3,
        Desktop,
        Element,
        Element1,
        GroupName,
        Header,
        Image,
        Item,
        Mobile,
        Paging,
        Style,
        Style1,
        Style2,
        Style3,
        Tablet,
        Tag,
        Text,
        Tv,
        VodModel,
    )

__all__ = [
    "Action",
    "Action1",
    "Action2",
    "Action3",
    "Action4",
    "Attributes",
    "Attributes1",
    "Attributes2",
    "Attributes3",
    "Attributes4",
    "Attributes5",
    "Attributes6",
    "Attributes7",
    "Attributes8",
    "Attributes9",
    "Button",
    "ContentDownload",
    "ContentItem",
    "Data",
    "Data1",
    "Data3",
    "Desktop",
    "Element",
    "Element1",
    "GroupName",
    "Header",
    "Image",
    "Item",
    "Mobile",
    "Paging",
    "Style",
    "Style1",
    "Style2",
    "Style3",
    "Tablet",
    "Tag",
    "Text",
    "Tv",
    "VodModel",
    "model_validate_json",
]


def model_validate_json(data: str | bytes | object, log_id: str) -> VodModel:
    """Read a downloaded file into VodModel."""
    return load.model_validate_json(StrictModel, OptionalModel, data, log_id)
