# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: None
    image: None
    actions: None
    content: None
    type: None
    id: None
    active_tab: None
    items: None
    text: str
    label: str
    tab: None
    paging: None


class Mobile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display: str


class Tablet(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    display: str


class Style(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    desktop: None
    tv: None
    mobile: Mobile
    tablet: Tablet


class VodTextBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    field_zone: str
    attributes: Attributes
    style: Style
