# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Series(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    series_id: int
    title: str


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str
    long_description: str
    season_number: int
    episode_count: int
    id: int
    series: Series


class Paging(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    more_data_available: bool


class Seasons(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    items: list[Item]
    paging: Paging


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: None
    image: None
    actions: None
    content: None
    id: int
    type: str
    active_tab: None
    items: None
    series: Series
    season_id: int
    seasons: Seasons
    tab: None
    bucket_title: None
    series_id: None
    paging: None
    text: None
    label: None


class SeasonSeries(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    field_zone: str
    attributes: Attributes
    style: None
