# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class PrecedingSeason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str
    long_description: str = Field(..., alias="longDescription")
    small_cover_url: str = Field(..., alias="smallCoverUrl")
    cover_url: str = Field(..., alias="coverUrl")
    title_url: str = Field(..., alias="titleUrl")
    poster_url: str = Field(..., alias="posterUrl")
    season_number: int = Field(..., alias="seasonNumber")
    episode_count: int = Field(..., alias="episodeCount")
    displayable_tags: list[None] = Field(..., alias="displayableTags")
    upcoming_releases: list[None] = Field(..., alias="upcomingReleases")
    id: int


class FollowingSeason(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str
    long_description: str = Field(..., alias="longDescription")
    small_cover_url: str = Field(..., alias="smallCoverUrl")
    cover_url: str = Field(..., alias="coverUrl")
    title_url: str = Field(..., alias="titleUrl")
    poster_url: str = Field(..., alias="posterUrl")
    season_number: int = Field(..., alias="seasonNumber")
    episode_count: int = Field(..., alias="episodeCount")
    displayable_tags: list[None] = Field(..., alias="displayableTags")
    upcoming_releases: list[None] = Field(..., alias="upcomingReleases")
    id: int


class PrecedingItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str
    long_description: str = Field(..., alias="longDescription")
    small_cover_url: str = Field(..., alias="smallCoverUrl")
    cover_url: str = Field(..., alias="coverUrl")
    title_url: str = Field(..., alias="titleUrl")
    poster_url: str = Field(..., alias="posterUrl")
    season_number: int = Field(..., alias="seasonNumber")
    episode_count: int = Field(..., alias="episodeCount")
    displayable_tags: list[None] = Field(..., alias="displayableTags")
    upcoming_releases: list[None] = Field(..., alias="upcomingReleases")
    id: int


class FollowingItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    title: str
    description: str
    long_description: str = Field(..., alias="longDescription")
    small_cover_url: str = Field(..., alias="smallCoverUrl")
    cover_url: str = Field(..., alias="coverUrl")
    title_url: str = Field(..., alias="titleUrl")
    poster_url: str = Field(..., alias="posterUrl")
    season_number: int = Field(..., alias="seasonNumber")
    episode_count: int = Field(..., alias="episodeCount")
    displayable_tags: list[None] = Field(..., alias="displayableTags")
    upcoming_releases: list[None] = Field(..., alias="upcomingReleases")
    id: int


class WatchOrder(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preceding: list[PrecedingItem]
    following: list[FollowingItem]


class OtherSeasons(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    preceding_seasons: list[PrecedingSeason] = Field(..., alias="precedingSeasons")
    following_seasons: list[FollowingSeason] = Field(..., alias="followingSeasons")
    watch_order: WatchOrder = Field(..., alias="watchOrder")
