# ruff: noqa: D100, D101
# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class ContentDownload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permission: str


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: int
    type: str
    title: str
    description: str
    long_description: str = Field(..., alias="longDescription")
    content_download: ContentDownload | None = Field(None, alias="contentDownload")
    cover_url: str = Field(..., alias="coverUrl")
    small_cover_url: str = Field(..., alias="smallCoverUrl")
    season_count: str = Field(..., alias="seasonCount")
    poster_url: str = Field(..., alias="posterUrl")
    access_level: str = Field(..., alias="accessLevel")
    favourite: bool
    watch_status: str = Field(..., alias="watchStatus")
    favourite_channel: str = Field(..., alias="favouriteChannel")
    has_permission: bool = Field(..., alias="hasPermission")
    is_related: bool = Field(..., alias="isRelated")
    has_permission_granted_on_sign_in: bool = Field(
        ...,
        alias="hasPermissionGrantedOnSignIn",
    )


class GroupName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    label: str


class Paging(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    more_data_available: bool = Field(..., alias="moreDataAvailable")
    last_seen: str = Field(..., alias="lastSeen")


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    items: list[Item]
    tab: str
    bucket_title: str | None = Field(None, alias="bucketTitle")
    group_name: GroupName | None = Field(None, alias="groupName")
    paging: Paging


class VodBucket(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str = Field(..., alias="$type")
    field_zone: str = Field(..., alias="$zone")
    attributes: Attributes
