# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: None
    attributes: None
    id: int
    type: str
    title: str
    description: str
    long_description: str
    cover_url: str
    small_cover_url: str
    season_count: str
    poster_url: str
    access_level: str
    favourite: bool
    watch_status: str
    favourite_channel: str
    has_permission: bool
    is_related: bool
    has_permission_granted_on_sign_in: bool


class Paging(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    more_data_available: bool
    last_seen: str


class Attributes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    header: None
    image: None
    actions: None
    content: None
    type: str
    id: None
    active_tab: None
    items: list[Item]
    text: None
    label: None
    tab: str
    paging: Paging


class VodBucket(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    field_type: str
    field_zone: str
    attributes: Attributes
    style: None
